# Generated by Django 3.1.2 on 2022-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='receta',
            field=models.CharField(choices=[(1, 's'), (2, 'n')], max_length=1, verbose_name='Receta'),
        ),
        migrations.AlterField(
            model_name='medicos',
            name='especialidad',
            field=models.CharField(choices=[(1, 'familia'), (2, 'digestivo'), (3, 'neurólogo'), (4, 'dermatólogo'), (5, 'traumatólogo')], max_length=40, verbose_name='Especialidad'),
        ),
    ]
