# Generated by Django 3.1.2 on 2022-04-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0002_auto_20220422_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citas',
            new_name='Cita',
        ),
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
        migrations.RenameModel(
            old_name='ComprasMedicamentos',
            new_name='CompraMedicamento',
        ),
        migrations.RenameModel(
            old_name='Medicamentos',
            new_name='Medicamento',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
