# Generated by Django 3.1.2 on 2022-04-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0003_auto_20220422_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(upload_to='pacientes', verbose_name='Foto'),
        ),
    ]
