# Generated by Django 3.1.2 on 2022-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0006_paciente_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(unique=True, upload_to='fotos_pacientes/', verbose_name='Foto'),
        ),
    ]
