# Generated by Django 3.1.2 on 2022-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0007_auto_20220504_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='receta',
            field=models.CharField(choices=[('s', 'Con receta'), ('n', 'Sin receta')], default='s', max_length=1, verbose_name='Receta'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('familia', 'familia'), ('digestivo', 'digestivo'), ('neurólogo', 'neurólogo'), ('dermatólogo', 'dermatólogo'), ('traumatólogo', 'traumatólogo')], default='familia', max_length=40, verbose_name='Especialidad'),
        ),
    ]
