# Generated by Django 3.1.2 on 2022-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0008_auto_20220509_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='receta',
            field=models.CharField(choices=[('s', 'Con receta'), ('n', 'Venta libre')], default='s', max_length=1, verbose_name='Receta'),
        ),
    ]
