# Generated by Django 3.1.2 on 2022-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0009_auto_20220514_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='receta',
            field=models.CharField(choices=[('s', 's'), ('n', 'n')], default='s', max_length=1, verbose_name='Receta'),
        ),
    ]
