# Generated by Django 3.1.2 on 2022-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0013_auto_20220524_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(default='Seleccione un médico', on_delete=django.db.models.deletion.CASCADE, to='seguroprivado.paciente', verbose_name='Paciente'),
        ),
    ]
