# Generated by Django 3.1.2 on 2022-05-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0014_auto_20220525_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idMedico',
            field=models.ForeignKey(default='Seleccione un médico', on_delete=django.db.models.deletion.CASCADE, to='seguroprivado.medico', verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(default='Seleccione un paciente', on_delete=django.db.models.deletion.CASCADE, to='seguroprivado.paciente', verbose_name='Paciente'),
        ),
    ]
