# Generated by Django 3.1.2 on 2022-05-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0015_auto_20220525_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(default='Seleccione un paciente', editable=False, on_delete=django.db.models.deletion.CASCADE, to='seguroprivado.paciente', verbose_name='Paciente'),
        ),
    ]
