# Generated by Django 3.1.2 on 2022-05-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0017_auto_20220525_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='idPaciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seguroprivado.paciente', verbose_name='Paciente'),
        ),
    ]
