# Generated by Django 3.1.2 on 2022-06-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroprivado', '0018_auto_20220526_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tratamiento'),
        ),
    ]
